name: learncpp-datavisualizatorapp-gtests-workflow

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: cmake files
      run: bash scripts/cmake.sh
    - name: make tests
      run: bash scipts/make.sh tests.exe
    - name: Run Test
      run: bash tests.exe